name: marvel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - 'assets/icons/marvel_logo.svg'
    - 'assets/images/bg_1.png'
    - 'assets/images/bg_2.png'
    - 'assets/images/bg_3.png'
    - 'assets/images/bg_4.png'
    - 'assets/images/bg_5.png'
    - 'assets/images/bg_6.png'
  uses-material-design: true
